# Generated by Django 6.0.3 on 2026-04-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Product',
            new_name='product',
        ),
    ]
