# Generated by Django 6.0.3 on 2026-04-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_product_stock_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('branch', 'product')},
        ),
    ]
