# Generated by Django 6.0.3 on 2026-04-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'location')},
        ),
    ]
